#!/usr/bin/env bash

alias fh='open -a Finder .'
alias flush='dscacheutil -flushcache'
eject() {
  osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
}

alias resetsound='sudo killall coreaudiod'

selected() {
  osascript <<EOT
        tell application "Finder"
            set theFiles to selection
            set theList to ""
            repeat with aFile in theFiles
                set theList to theList & POSIX path of (aFile as alias) & "\n"
            end repeat
            theList
        end tell
EOT
}

finder_path() {
  osascript -e 'tell application "Finder"' \
    -e "if (${1-1} <= (count Finder windows)) then" \
    -e "get POSIX path of (target of window ${1-1} as alias)" \
    -e 'else' \
    -e 'get POSIX path of (desktop as alias)' \
    -e 'end if' \
    -e 'end tell'
}

# brew install
bip() {
  local -r inst=$(brew search | fzf -m)
  if [[ $inst ]]; then
    for prog in $(echo $inst); do brew install $prog; done
  fi
}
