#!/usr/bin/env bash
set -e

defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false
defaults write -app Skim SKAutoReloadFileUpdate -boolean true
defaults write NSGlobalDomain AppleHighlightColor -string "1.000000 0.937255 0.690196"
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
