#!/usr/bin/env bash
set -e

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing sudo time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd "${BASH_SOURCE%/*}"

if test ! "$(which brew)"; then
  echo "> Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "> Updating homebrew"
brew update

echo "> Installing brews"
brew bundle
brew bundle check

if [ "$SHELL" == '/bin/bash' ]; then
  echo "> Setting up bash"
  grep -q -F "$(brew --prefix)/bin/bash" /etc/shells || echo "$(brew --prefix)/bin/bash" | sudo tee -a /etc/shells
  sudo chsh -s "$(brew --prefix)/bin/bash" "$USER"
fi

echo "> Clearing homebrew caches"
brew cleanup
brew cask cleanup

echo "> Setting up dock"
./dock

echo "> Setting defaults"
./defaults
