# If not running interactively, don't do anything
if [[ $- != *i* ]]; then return; fi

# get real path to dotfiles repo
DOTFILES="$(dirname $(readlink ${BASH_SOURCE%}))/../.."

# set color scheme
BASE16_THEME='base16-default-dark'
BASE16_SHELL="$DOTFILES/bash/${BASE16_THEME}.sh"
[[ -f $BASE16_SHELL ]] && source $BASE16_SHELL

"$DOTFILES/bash/bin/term_scheme" "#282c34"

# https://github.com/mrzool/bash-sensible
. $DOTFILES/bash/sensible.bash

# set prompt
export PROMPT_EMOJI=1
. $DOTFILES/bash/prompt

# setup MacOS specific config
if [ "$(uname)" == "Darwin" ]; then
  . "$DOTFILES/macos/bashrc"
fi

# https://github.com/clvv/fasd
if hash fasd 2>/dev/null; then
  :
else
  # source fasd from dotfiles if not installed globally
  . "$DOTFILES/bash/fasd"
fi
eval "$(fasd --init auto)"

export PATH=$PATH:$DOTFILES/bash/bin

export EDITOR=vim

. $DOTFILES/bash/fzf-config
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# source bash aliases
. $DOTFILES/bash/bash_aliases
. $DOTFILES/private/bash/bash_aliases 2>/dev/null

unset DOTFILES
