#!/usr/bin/env bash

alias reload='source ~/.bashrc'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias -- -='cd -'
alias sl=ls

case "$OSTYPE" in
darwin*) alias ls='ls -G' ;;
linux*) alias ls='ls --color=auto' ;;
esac

alias la='ls -AF'
alias ll='ls -alh'
alias l='ls -a'
alias l1='ls -1'
alias q='exit'
alias c="clear; printf '\e[3J'"
alias gs='git status'
alias gp='git push origin master'
alias gr='git rev-parse --is-inside-work-tree && cd $(git rev-parse --show-toplevel)'

# log vim keystrokes for science
alias vim="vim -w ~/.vimlog $@"
alias v="vim"
# v() {
#   vim "$@";
#   $DOTFILES/bash/bin/term_scheme "#005000"
# }

swap() {
  tmpfile="$(mktemp "$(dirname "$1")/XXXXXX")"
  mv "$1" "$tmpfile" && mv "$2" "$1" && mv "$tmpfile" "$2"
}
